# Generated by Django 5.2.4 on 2025-07-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_review_product_reviews_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviews_no',
            field=models.IntegerField(editable=False),
        ),
    ]
